import os

from pelican_jupyter import markup as nb_markup

AUTHOR = 'Thomas Boggs'
SITENAME = 'blog.bogatron.net'
SITESUBTITLE = u'A blog mostly about Python, Machine Learning, and Remote Sensing.'
SITEURL = ''

PATH = 'content'

# Times and dates.
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'America/New_York'
DEFAULT_LANG = u'en'

# Set the article URL.
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options.
MENUITEMS = [('Archives', '/archives.html'),]
#             ('Home Page', '')]
NEWEST_FIRST_ARCHIVES = True

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Spectral Python (SPy)', 'http://spectralpython.net'),)

# Social widget
#SOCIAL = (('You can add links in your config file', '#'),
#          ('Another social link', '#'),)

#DEFAULT_PAGINATION = False
DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = False

# my additions
CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'content'
#STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png', 'images', 'extra/CNAME']
STATIC_PATHS = ['images', 'downloads', 'extra/CNAME']
EXTRA_PATH_METADATA = {'extra/CNAME': {'path': 'CNAME'},}

# Theme and plug-ins.
path = os.path.abspath('..')
THEME = os.path.join(path, 'themes/pelican-octopress-theme2')
PLUGINS = [nb_markup]
MARKUP = ('md', 'ipynb')
IGNORE_FILES = [".ipynb_checkpoints"]  

# This header file is automatically generated by the notebook plugin.
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found. "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read()

# Sharing
#TWITTER_USER = 'xxx'
#GOOGLE_PLUS_ID = '+ThomasBoggs'
#GOOGLE_PLUS_ONE = True
#GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = True
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
#TWITTER_FOLLOW_BUTTON = True
#TWITTER_TWEET_COUNT = 3
#TWITTER_SHOW_REPLIES = 'false'
#TWITTER_SHOW_FOLLOWER_COUNT = 'true'

# RSS/Atom feeds
FEED_DOMAIN = SITEURL
FEED_ATOM = 'atom.xml'

# Search
SEARCH_BOX = True
