#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os

AUTHOR = u'Thomas Boggs'
SITENAME = u'blog.bogatron.net'
SITESUBTITLE = u'A blog mostly about Python, Machine Learning, and Remote Sensing.'
SITEURL = '' # Change in publishconf.py and ignore the WARNING.

# Times and dates.
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'America/New_York'
DEFAULT_LANG = u'en'

# Set the article URL.
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options.
MENUITEMS = [('Archives', '/archives.html'),]
#             ('Home Page', '')]
NEWEST_FIRST_ARCHIVES = False

# Github include settings.
#GITHUB_USER = 'tboggs'
#GITHUB_REPO_COUNT = 5
#GITHUB_SKIP_FORK = True
#GITHUB_SHOW_USER_LINK = True

# Blogroll.
LINKS = (('Spectral Python (SPy)', 'http://spectralpython.net'),)

# Social widget.
#SOCIAL = (('You can add links in your config file', '#'),
          #('Another social link', '#'),)

DEFAULT_PAGINATION = 10

# STATIC_OUT_DIR requires pelican 3.3+.
#STATIC_OUT_DIR = ''
#FILES_TO_COPY = [('favicon.png', 'favicon.png')]
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png', 'images', 'extra/CNAME']
EXTRA_PATH_METADATA = {'extra/CNAME': {'path': 'CNAME'},}

CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'

# Theme and plug-ins.
path = os.path.abspath('..')
THEME = os.path.join(path, 'themes/pelican-octopress-theme')
PLUGIN_PATH = os.path.join(path, 'pelican-plugins')
PLUGINS = ['summary', 'liquid_tags.img', 'liquid_tags.video',
           'liquid_tags.include_code', 'liquid_tags.notebook',
           'liquid_tags.literal']

# This header file is automatically generated by the notebook plugin.
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found. "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

# Sharing
#TWITTER_USER = 'xxx'
GOOGLE_PLUS_ID = '+ThomasBoggs'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = True
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
#TWITTER_FOLLOW_BUTTON = True
#TWITTER_TWEET_COUNT = 3
#TWITTER_SHOW_REPLIES = 'false'
#TWITTER_SHOW_FOLLOWER_COUNT = 'true'

# RSS/Atom feeds
FEED_DOMAIN = SITEURL
FEED_ATOM = 'atom.xml'

# Search
SEARCH_BOX = True
